server:
  port: 23001
  max-http-header-size: 1024000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pms
    druid:
      max-active: 2
      initial-size: 1
      filter: stat
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-open-prepared-statements: 20
      pool-prepared-statements: true
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
